#!/bin/bash

green="\e[32m"
nocolor="\e[0m"
cyan="\e[36m"
red='\033[0;31m'
yellow='\033[1;33m'
newline="--------------"
echo -e "${cyan}

 _____                    ________     _       _   
/  ___|                  / _| ___ \   (_)     | |  
\ \`--. _ __   ___   ___ | |_| |_/ /__  _ _ __ | |_ 
 \`--. \ '_ \ / _ \ / _ \|  _|  __/ _ \| | '_ \| __|
/\__/ / |_) | (_) | (_) | | | | | (_) | | | | | |_ 
\____/| .__/ \___/ \___/|_| \_|  \___/|_|_| |_|\__|
      | |                                          
      |_|                                          
--------------------------------------------------------------
${nocolor}
"
while getopts d:i: flag
do 
    case "${flag}" in 
        d) domain=${OPTARG};;
        i) input=${OPTARG};;
    esac
done

#Check if there is no input
if [ $# -eq 0 ]; then
    echo 'Please use -d <Domain>'
    exit 1
fi

# Check if single domain exists
if [ -n "$domain" ]; then
    whois $domain | head | grep "Domain Name" > /dev/null 2>&1
    if [ $? == 0 ]; then
        echo -e "\n${red}$newline $domain exists$newline${nocolor}"
        whois $domain | head -n 15 
        dig $domain mx | grep -U2 ";; ANSWER" > /dev/null 2>&1
        if [ $? == 0 ]; then
            echo -e "${yellow}This domain has MX records set up!\n${nocolor}"
        else
            echo -e "${yellow}This domain does not have MX records set up${nocolor}"
        fi
        exit 0
    fi 
    echo "Domain does not exist"
    exit 0
fi


if [ -n "$input" ]; then
    while IFS= read -r line; do
        whois $line| head | grep "Domain Name" > /dev/null 2>&1
        if [ $? == 0 ]; then
            echo -e "\n${red}$newline $line exists$newline${nocolor}"
            whois $line| head -n 15 
            dig $line mx | grep -U2 ";; ANSWER" > /dev/null 2>&1
            if [ $? == 0 ]; then
                echo -e "${yellow}This domain has MX records set up!\n${nocolor}"
            else
                echo -e "${yellow}This domain does not have MX records set up${nocolor}"
            fi
        else
            echo -e "${green}$line is not a valid domain"
        fi
    done < $input 

fi
